In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df_address = pd.read_csv('C:/Users/Admin/Desktop/project/data/대여소정보.csv', encoding='cp949')
df_address.head()

     보관소(대여소)명 소재지(위치)
0   망원역 1번출구 앞     마포구
1   망원역 2번출구 앞     마포구
2   합정역 1번출구 앞     마포구
3   합정역 5번출구 앞     마포구
4   합정역 7번출구 앞     마포구

In [4]:
df_data = pd.read_csv('C:/Users/Admin/Desktop/project/data_clean/20/01_전처리완료.csv', encoding='cp949')
df_data.head()

                  대여일시         대여 대여소명                 반납일시        반납대여소명
0  2020-01-01 00:01:04            송도병원  2020-01-01 00:04:21    약수역 3번출구 뒤
1  2020-01-01 00:02:53  KT 전화국 버스정류장 옆  2020-01-01 00:04:48  중앙하이츠 아파트 입구
2  2020-01-01 00:01:21       삼부르네상스파크빌  2020-01-01 00:05:51     디지털입구 교차로
3  2020-01-01 00:03:12        대흥역 1번출구  2020-01-01 00:05:54      서강대 후문 옆
4  2020-01-01 00:01:11     마곡엠밸리10단지 앞  2020-01-01 00:05:57        마곡역교차로

In [5]:
def get_gu(addr):
    if pd.isna(addr):
        return None
    for token in str(addr).split():
        if token.endswith('구'):
            return token
    return None

In [6]:
df_address['자치구'] = df_address['소재지(위치)'].apply(get_gu)

In [7]:
gu_map = (
    df_address.drop_duplicates('보관소(대여소)명')
                .set_index('보관소(대여소)명')['자치구']
                .to_dict()
)

In [8]:
df_data['대여 자치구'] = df_data['대여 대여소명'].apply(lambda x: gu_map.get(x))
df_data['반납 자치구'] = df_data['반납대여소명'].apply(lambda x: gu_map.get(x))

In [9]:
df_data[df_data['대여 자치구'].isna()]['대여 대여소명'].unique()

array(['송도병원', 'KT 전화국 버스정류장 옆', '삼부르네상스파크빌', ..., '상암센터', '중랑센터', '개화센터'],
      dtype=object)

In [10]:
df_address['보관소(대여소)명'] = df_address['보관소(대여소)명'].str.strip()
df_data['대여 대여소명'] = df_data['대여 대여소명'].str.strip()
df_data['반납대여소명'] = df_data['반납대여소명'].str.strip()

In [11]:
df_data['대여 자치구'] = df_data['대여 대여소명'].map(gu_map)
df_data['반납 자치구'] = df_data['반납대여소명'].map(gu_map)

In [12]:
print(df_address[['보관소(대여소)명', '소재지(위치)', '자치구']].head(10))
print(df_address['자치구'].isna().sum(), '/', len(df_address))

      보관소(대여소)명 소재지(위치)  자치구
0    망원역 1번출구 앞     마포구  마포구
1    망원역 2번출구 앞     마포구  마포구
2    합정역 1번출구 앞     마포구  마포구
3    합정역 5번출구 앞     마포구  마포구
4    합정역 7번출구 앞     마포구  마포구
5    신한은행 서교동지점     마포구  마포구
6       서교동 사거리     마포구  마포구
7    상수역 2번출구 앞     마포구  마포구
8  홍대입구역 2번출구 앞     마포구  마포구
9  홍대입구역 8번출구 앞     마포구  마포구
0 / 2789

In [13]:
print(df_address['보관소(대여소)명'].head(10).tolist())
print(df_data['대여 대여소명'].head(10).tolist())

['망원역 1번출구 앞', '망원역 2번출구 앞', '합정역 1번출구 앞', '합정역 5번출구 앞', '합정역 7번출구 앞', '신한은행 서교동지점', '서교동 사거리', '상수역 2번출구 앞', '홍대입구역 2번출구 앞', '홍대입구역 8번출구 앞']
['송도병원', 'KT 전화국 버스정류장 옆', '삼부르네상스파크빌', '대흥역 1번출구', '마곡엠밸리10단지 앞', '서울북부고용센터앞', '원묵고등학교', '서울 월드컵 경기장', '천왕역 1번 출입구 앞', '영등포구청역 7번출구']

In [14]:
df_address['보관소(대여소)명'] = df_address['보관소(대여소)명'].astype(str).str.strip()
df_data['대여 대여소명'] = df_data['대여 대여소명'].astype(str).str.strip()
df_data['반납대여소명'] = df_data['반납대여소명'].astype(str).str.strip()

gu_map = df_address.drop_duplicates('보관소(대여소)명').set_index('보관소(대여소)명')['자치구'].to_dict()

df_data['대여 자치구'] = df_data['대여 대여소명'].map(gu_map)
df_data['반납 자치구'] = df_data['반납대여소명'].map(gu_map)

In [15]:
import re

def clean_name(x):
    return re.sub(r'^\d+\.\s*', '', str(x)).strip()

df_address['보관소(대여소)명'] = df_address['보관소(대여소)명'].apply(clean_name)
df_data['대여 대여소명'] = df_data['대여 대여소명'].apply(clean_name)
df_data['반납대여소명'] = df_data['반납대여소명'].apply(clean_name)

In [21]:
df_data.tail()

,대여일시,대여 대여소명,반납일시,반납대여소명,대여 자치구,반납 자치구
789034,2020-01-31 18:07:26,수협 연남동지점,2020-02-01 07:36:26,망원1동주민센터,NaN,NaN
789035,2020-01-31 21:34:56,장안동 사거리,2020-02-01 07:59:20,면목4치안센터,동대문구,중랑구
789036,2020-01-31 21:03:53,염창역 1번 출구,2020-02-01 08:23:05,KB국민은행 염창역 지점 앞,강서구,양천구
789037,2020-01-31 11:14:07,을지로4가역 1번출구,2020-02-01 09:54:56,을지로4가역 1번출구,중구,중구
789038,2020-01-31 10:56:36,을지로4가역 1번출구,2020-02-01 09:55:00,을지로4가역 1번출구,중구,중구

In [23]:
mask = df_data['대여 자치구'].isna() | df_data['반납 자치구'].isna()
df_missing = df_data[mask]
print(df_missing)
print(len(df_missing))

                       대여일시             대여 대여소명                 반납일시  \
3       2020-01-01 00:03:12            대흥역 1번출구  2020-01-01 00:05:54
9       2020-01-01 00:02:05         영등포구청역 7번출구  2020-01-01 00:07:59
12      2020-01-01 00:03:26          신대방역 2번 출구  2020-01-01 00:09:04
15      2020-01-01 00:02:29  생명의 전화 종합복지관 앞 교차로  2020-01-01 00:09:28
23      2020-01-01 00:03:46               사근삼거리  2020-01-01 00:11:59
...                     ...                 ...                  ...
789025  2020-01-31 22:14:01             경일중학교 앞  2020-02-01 01:20:11
789029  2020-01-31 23:45:11            신당동주민센터앞  2020-02-01 01:27:57
789030  2020-01-31 23:40:28           서울숲 관리사무소  2020-02-01 01:30:45
789031  2020-01-31 23:40:31           서울숲 관리사무소  2020-02-01 01:33:45
789034  2020-01-31 18:07:26            수협 연남동지점  2020-02-01 07:36:26

                      반납대여소명 대여 자치구 반납 자치구
3                   서강대 후문 옆    NaN    마포구
9               양평동6차현대아파트 앞    NaN   영등포구
12                 신림동 우방아파트    NaN    관악구
15                     미아사거리    성북구    NaN
23              장한평역 8번 출구 앞    NaN    성동구
...                      ...    ...    ...
789025          성수아이에스비즈타워 앞    성동구    NaN
789029  복정역 2번출구 후문 (장지치안센터)    NaN    NaN
789030       래미안 강동팰리스(102동)    NaN    강동구
789031         올림픽공원역 1번출구 앞    NaN    송파구
789034              망원1동주민센터    NaN    NaN

[181827 rows x 6 columns]
181827